/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "caesar_minus2_gross_tests.ts" instead.
 */

#include <check.h>

#line 1 "caesar_minus2_gross_tests.ts"
#include "caesar_minus2_gross.h"

// checkmk caesar_minus2_gross_tests.ts > caesar_minus2_gross_tests.c
// gcc caesar_minus2_gross.c caesar_minus2_gross_tests.c -o tests -Wall -lsubunit -lm -lpthread -lrt -lcheck -std=c99 -g -fprofile-arcs -ftest-coverage

START_TEST(caesar_E_to_C)
{
#line 7
    char to_test[] = "E";
    caesar(to_test);

    char res[] = "C";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(caesar_A_to_Y)
{
#line 15
    char to_test[] = "A";
    caesar(to_test);

    char res[] = "Y";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(caesar_B_to_Z)
{
#line 23
    char to_test[] = "B";
    caesar(to_test);

    char res[] = "Z";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(caesar_longer_string)
{
#line 31
    char to_test[] ="DIESISTEINLANGERSTRING";
    caesar(to_test);
    
    char res[] = "BGCQGQRCGLJYLECPQRPGLE";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(caesar_really_long_string)
{
#line 39
    char to_test[] ="ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ";
    caesar(to_test);
    
    char res[] = "YZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(encode_and_compare_true_short)
{
#line 47
    char string_to_encode[] = "A";
    char clearstring[] = "Y";
    ck_assert_int_eq(encode_and_compare(clearstring, string_to_encode), 1);


}
END_TEST

START_TEST(encode_and_compare_true_long)
{
#line 53
    char string_to_encode[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ";
    char clearstring[] = "YZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX";
    ck_assert_int_eq(encode_and_compare(clearstring, string_to_encode), 1);


}
END_TEST

START_TEST(encode_and_compare_false)
{
#line 59
    char string_to_encode[] = "A";
    char clearstring[] = "A";
    ck_assert_int_eq(encode_and_compare(clearstring, string_to_encode), 0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, caesar_E_to_C);
    tcase_add_test(tc1_1, caesar_A_to_Y);
    tcase_add_test(tc1_1, caesar_B_to_Z);
    tcase_add_test(tc1_1, caesar_longer_string);
    tcase_add_test(tc1_1, caesar_really_long_string);
    tcase_add_test(tc1_1, encode_and_compare_true_short);
    tcase_add_test(tc1_1, encode_and_compare_true_long);
    tcase_add_test(tc1_1, encode_and_compare_false);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
