/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "simpleString_tests.ts" instead.
 */

#include <check.h>

#line 1 "simpleString_tests.ts"
#include <string.h>
#include "simpleString.h"

// Tests bauen und ausführen:
// checkmk simpleString_tests.ts > simpleString_tests.c
// gcc simpleString.c simpleString_tests.c -o tests -Wall $(pkg-config --cflags --libs check) -std=c99 -g
// ./tests

START_TEST(length_of_empty_string)
{
#line 10
    char * string = "";
    int result = my_strlen(string);
    ck_assert_int_eq(0, result);

}
END_TEST

START_TEST(length_of_string)
{
#line 15
    char * string = "Hallo Welt";
    int result = my_strlen(string);
    ck_assert_int_eq(10, result);

}
END_TEST

START_TEST(array_is_no_string)
{
#line 20
    char array[] ={'a', 'b', 'c'};
    int len = 3;
    int result = is_string(array, len);
    ck_assert_int_eq(0, result);

}
END_TEST

START_TEST(empty_string_is_string)
{
#line 26
    char *empty = "";
    int len = 1;
    int result = is_string(empty, len);
    ck_assert_int_eq(1, result);

}
END_TEST

START_TEST(string_is_string)
{
#line 32
    char *string = "hallo";
    int len = 6;
    int result = is_string(string, len);
    ck_assert_int_eq(1, result);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, length_of_empty_string);
    tcase_add_test(tc1_1, length_of_string);
    tcase_add_test(tc1_1, array_is_no_string);
    tcase_add_test(tc1_1, empty_string_is_string);
    tcase_add_test(tc1_1, string_is_string);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
