/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "casts_tests.ts" instead.
 */

#include <check.h>

#line 1 "casts_tests.ts"
#include "casts.h"

START_TEST(drei_durch_twei)
{
#line 4
    float ergebnis = dividiere(3, 2);

    ck_assert_int_eq(ergebnis * 2, 3);

}
END_TEST

START_TEST(drei_durch_drei)
{
#line 9
    float ergebnis = dividiere(3, 3);

    ck_assert_int_eq(ergebnis * 3, 3);

}
END_TEST

START_TEST(zwei_durch_vier)
{
#line 14
    float ergebnis = dividiere(2, 4);

    ck_assert_int_eq(ergebnis * 4, 2);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, drei_durch_twei);
    tcase_add_test(tc1_1, drei_durch_drei);
    tcase_add_test(tc1_1, zwei_durch_vier);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
