/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "count_all_tests.ts" instead.
 */

#include <check.h>

#line 1 "count_all_tests.ts"
#include "count_all.h"
#include <string.h>

// checkmk count_all_tests.ts > count_all_tests.c
// gcc count_all.c count_all_tests.c -o tests -Wall -lsubunit -lm -lpthread -lrt -lcheck -std=c99 -g -fprofile-arcs -ftest-coverage

void check_token_array(int cnt_tokens, int *mycount, int *count, char mytokens[][80]){
    for(int i = 0; i < cnt_tokens; i++){
        int token_found = 0;
        for(int j = 0; j < cnt_tokens; j++){
            if(strcmp(mytokens[i], tokens[j]) == 0 ){
                token_found++;
                ck_assert_msg(count[j] == mycount[i], "Anzahl für Wort %s nicht korrekt. Ist %i, soll %i.\n", mytokens[i], count[j], mycount[i]);
            }
        }
        if(token_found == 0){
            ck_abort_msg("Wort %s in tokens nicht gefunden!\n", mytokens[i]);
        } else if (token_found > 1) {
            ck_abort_msg("Wort %s in tokens zu oft gefunden!\n", mytokens[i]);
        }
    }
}

START_TEST(extract_and_count_without_special_chars_return_value)
{
#line 25
    char string[] = "Wort1 Wort2 wort1 Wort1 Wort1 Wort4 Wort3 Wort3";
    int count[80]; 
    ck_assert_int_eq(extract_and_count(string, count), 5);

}
END_TEST

START_TEST(extract_and_count_without_special_chars_check_arrays)
{
#line 30
    char string[] = "Wort1 Wort2 wort1 Wort1 Wort1 Wort4 Wort3 Wort3";
    char mytokens[][80] = {"Wort1", "Wort2", "wort1", "Wort4", "Wort3"};
    int mycount[] = {3, 1, 1, 1, 2};
    int cnt_tokens = 5;
    int count[80]; 
    extract_and_count(string, count);
    check_token_array(cnt_tokens, mycount, count, mytokens);

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, extract_and_count_without_special_chars_return_value);
    tcase_add_test(tc1_1, extract_and_count_without_special_chars_check_arrays);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
